"""Create a tiny plumbing dataset and YOLO/DOTA split manifests; not quality evidence."""
from pathlib import Path
import json, random
from PIL import Image, ImageDraw

ROOT=Path(__file__).resolve().parents[1]; demo=ROOT/"data"/"demo"; demo.mkdir(parents=True,exist_ok=True)
for i in range(3):
    image=Image.new("RGB",(1280,960),(31+i*8,44+i*8,48+i*8)); d=ImageDraw.Draw(image)
    d.rectangle((150+i*80,220,300+i*80,300),outline=(85,214,190),width=4); image.save(demo/f"pipeline_sample_{i}.png")
records=[{"file":p.name,"sha256":__import__('hashlib').sha256(p.read_bytes()).hexdigest()} for p in sorted(demo.glob("*.png"))]
random.Random(42).shuffle(records)
(demo/"manifest.json").write_text(json.dumps({"purpose":"Pipeline smoke tests only; no accuracy claim.","license":"Generated by this script; CC0-compatible.","train":records[:1],"val":records[1:2],"test":records[2:]},indent=2),encoding="utf-8")
print(demo/"manifest.json")
